name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
          - windows
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10.0-beta.4
          - pypy-3.7

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dev dependencies
        # Forked commit
        run: python -m pip install https://github.com/ActiveState/appdirs/archive/8eacfa312d77aba28d483fbfb6f6fc54099622be.zip

      - name: Run tests
        run: python -m unittest discover
